version: '3.3'

services:
  linkflow-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: linkflow-admin
    ports:
      - "5000:5000"
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
      - FLASK_APP=admin/app.py
      - FLASK_ENV=production
    command: sh -c "Xvfb :99 -screen 0 1920x1080x24 & python admin/app.py"
    restart: always
    volumes:
      - ./screenshots:/app/screenshots
      - shared-storage:/tmp

  linkflow-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: linkflow-api
    ports:
      - "5001:5001"
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    command: sh -c "Xvfb :99 -screen 0 1920x1080x24 & python admin/api.py"
    restart: always
    volumes:
      - ./screenshots:/app/screenshots
      - shared-storage:/tmp

volumes:
  shared-storage:
